"""create kubernetes deployments table

Revision ID: 104f3e063d03
Revises: e2bf5d13871a
Create Date: 2026-10-07 10:09:23.628376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '104f3e063d03'
down_revision: Union[str, Sequence[str], None] = 'e2bf5d13871a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kubernetes_deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.Column('image_name', sa.String(length=255), nullable=False),
    sa.Column('application_name', sa.String(length=255), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('replicas', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kubernetes_deployments_environment_id'), 'kubernetes_deployments', ['environment_id'], unique=False)
    op.create_index(op.f('ix_kubernetes_deployments_project_id'), 'kubernetes_deployments', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kubernetes_deployments_project_id'), table_name='kubernetes_deployments')
    op.drop_index(op.f('ix_kubernetes_deployments_environment_id'), table_name='kubernetes_deployments')
    op.drop_table('kubernetes_deployments')
    # ### end Alembic commands ###
