"""add build project foreign key

Revision ID: 2bc773df7bd4
Revises: 7b76ccdc0c0f
Create Date: 2026-10-06 20:52:46.435674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bc773df7bd4'
down_revision: Union[str, Sequence[str], None] = '7b76ccdc0c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_builds_project_id_projects",
        "builds",
        "projects",
        ["project_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(
        "fk_builds_project_id_projects",
        "builds",
        type_="foreignkey",
   )
    # ### end Alembic commands ###
