"""add deployment pipeline runs

Revision ID: b21f7e0c2ffb
Revises: 104f3e063d03
Create Date: 2026-10-08 15:35:57.790130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b21f7e0c2ffb'
down_revision: Union[str, Sequence[str], None] = '104f3e063d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment_pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('repository_path', sa.String(length=500), nullable=False),
    sa.Column('image_name', sa.String(length=255), nullable=False),
    sa.Column('application_name', sa.String(length=255), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('replicas', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('security_scan_id', sa.Integer(), nullable=True),
    sa.Column('deployment_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('build_status', sa.String(length=50), nullable=False),
    sa.Column('validation_status', sa.String(length=50), nullable=False),
    sa.Column('security_status', sa.String(length=50), nullable=False),
    sa.Column('high_count', sa.Integer(), nullable=False),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ),
    sa.ForeignKeyConstraint(['deployment_id'], ['kubernetes_deployments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['security_scan_id'], ['security_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_pipeline_runs_build_id'), 'deployment_pipeline_runs', ['build_id'], unique=False)
    op.create_index(op.f('ix_deployment_pipeline_runs_deployment_id'), 'deployment_pipeline_runs', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_deployment_pipeline_runs_project_id'), 'deployment_pipeline_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_deployment_pipeline_runs_security_scan_id'), 'deployment_pipeline_runs', ['security_scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deployment_pipeline_runs_security_scan_id'), table_name='deployment_pipeline_runs')
    op.drop_index(op.f('ix_deployment_pipeline_runs_project_id'), table_name='deployment_pipeline_runs')
    op.drop_index(op.f('ix_deployment_pipeline_runs_deployment_id'), table_name='deployment_pipeline_runs')
    op.drop_index(op.f('ix_deployment_pipeline_runs_build_id'), table_name='deployment_pipeline_runs')
    op.drop_table('deployment_pipeline_runs')
    # ### end Alembic commands ###
