apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-gitops-demo
  namespace: nexus-gitops
  labels:
    app: nexus-gitops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-gitops-demo
  template:
    metadata:
      labels:
        app: nexus-gitops-demo
    spec:
      containers:
        - name: app
          image: nginx:1.27-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
